# Numpy is Numerical Python.

In [1]:
import numpy as np


# Numpy Functions

In [2]:
val1 = np.array([[1,2,3,4],[5,6,7,8]])
val1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

* np.zeros

In [3]:
val2 = np.zeros((8,5) , dtype=int)   # Default dtype = float
val2


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

* np.ones


In [4]:
val3 = np.ones((2,5) , dtype=int)
val3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

* np.arange


In [5]:
val4 = np.arange(6,40,2)
val4

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

* linspace

In [6]:
val5 = np.linspace(10,30,5)
val5

array([10., 15., 20., 25., 30.])

* random

In [7]:
val6 = np.random.randint(0,35,size=(4,6))
print(val6)

[[16 20 10 16  7 19]
 [ 0 28  6 12 27 25]
 [22 19  4  1 16 25]
 [24 13 17 10 31 29]]


* np.full

In [8]:
val7 = np.full((3,4,3),6)
print(val7)

[[[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]

 [[6 6 6]
  [6 6 6]
  [6 6 6]
  [6 6 6]]]


* identity

In [9]:
val8 = np.identity(5)
print(val8)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


* asarray

In [16]:
list_ = [1,2,3]
val9 = np.asarray(list_)
val9

array([1, 2, 3])

In [17]:
a = np.random.randint(1,5,(2,4))
a

array([[2, 3, 3, 1],
       [4, 4, 2, 2]])

In [19]:
k = np.random.randint(5,10,(2,4))
k

array([[6, 5, 8, 6],
       [8, 8, 7, 9]])

In [20]:
# Multiply
np.multiply(a,k)

array([[12, 15, 24,  6],
       [32, 32, 14, 18]])

In [21]:
# Divide 
np.divide(a,k)

array([[0.33333333, 0.6       , 0.375     , 0.16666667],
       [0.5       , 0.5       , 0.28571429, 0.22222222]])

In [25]:
# multiplication
multiply = np.multiply(186, 300)
multiply

55800

# Array Operations

In [32]:
val1 = np.random.randint(1,40,(3,5))
val1

array([[23,  5, 15, 32,  6],
       [12, 36, 20, 27, 18],
       [ 4,  8, 18, 21,  5]])

* max

In [33]:
val2.max()

0

* min

In [34]:
val3.min()

1

* Median

In [35]:
val4 = np.array([[1,2,3],[5,8,4]])
np.median(val4)

3.5

# Array Manipulation

In [36]:
val1 = np.array(np.random.randint(1,5,(4,6)))
val1

array([[4, 2, 1, 4, 1, 2],
       [3, 4, 1, 3, 3, 4],
       [4, 2, 1, 2, 4, 3],
       [4, 2, 4, 2, 1, 4]])

In [37]:
transpose_array = np.transpose(val1)
transpose_array

array([[4, 3, 4, 4],
       [2, 4, 2, 2],
       [1, 1, 1, 4],
       [4, 3, 2, 2],
       [1, 3, 4, 1],
       [2, 4, 3, 4]])

In [38]:
val2 = np.array(np.random.randint(5,8,(6,4)))
val2

array([[7, 6, 7, 7],
       [7, 7, 5, 7],
       [6, 7, 5, 6],
       [5, 6, 5, 7],
       [5, 6, 6, 7],
       [6, 7, 6, 6]])

In [39]:
val3.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Numpy array Attributes

ndarray.shape

In [42]:
val1 = np.array([[1,2,3],[3,4,9]])
print(val1.shape)

(2, 3)


In [43]:
val2 = np.array([[[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]],
                       [[1,2,3],[4,5,6]]])
print(val2.shape)

(4, 2, 3)


ndarray.ndim

In [45]:
val3 = np.array([[1,2,3],[4,5,6]])
print(f"The dimension of val3: ",val3.ndim)

The dimension of val3:  2


ndarray.dtype

In [46]:
val4 = np.array([1,2,3,4,5])
print(val4.dtype)

int32


ndarray.size

In [48]:
val5 = np.array([[1,2,3],[4,5,8]])
print(f"The total number of elements in val5 =  {val5.size}")

The total number of elements in val5 =  6


ndarray.astype

In [50]:
val6 = np.array([2,3,4])
print(val6.dtype)
print(val6)
print(val6_)

int32
[2 3 4]
[2. 3. 4.]
